version: '3.9'
services:
    apache:
        build: docker/apache
        container_name: sf4_apache
        ports:
          - 82:82
        volumes:
          - ./docker/config/vhosts:/etc/apache2/sites-enabled
          - ./docker/back_symf:/home/wwwroot/sf4
        depends_on:
          - php
        
    mysql:
        image: mysql:5.7
        container_name: sf4_mysql
        volumes:
            - ./docker/data/db:/var/lib/mysql
        ports:
          - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        
    php:
        build: docker/php
        container_name: sf4_php
        volumes:
          - ./docker/back_symf:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        ports:
          - 5432:5432
        depends_on:
          - maildev
          - mysql
        
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        restart: always
        ports:
            - 8080:8080
        links:
            - mysql
        environment:
          PMA_HOST: mysql
        
    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80
        
    nginx:
      container_name: angular_nginx
      build: docker/nginx
      volumes:
        - ./docker/front_ang/dist/Angular:/usr/share/nginx/html
      ports:
        - "81:81"
        - "443:443"
      
    node:
        build: docker/node
        container_name: angular_node
        ports:
            - 4200:4200
        volumes:
            - ./docker/front_ang:/home/node/app/frontend
        tty: true
        command:
            - /bin/sh
            - -c
            - |
                cd /home/node/app/frontend && npm start
        expose:
            - "4200"
networks:
    networks:
    project-network:
        driver: bridge